plugins {
    id 'com.android.application'
}

android {
    namespace 'com.shivsmile.indianstockpro'
    compileSdk 37

    defaultConfig {
        applicationId 'com.shivsmile.indianstockpro'
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
